'use client';

import { useState, useCallback } from 'react';
import ToolPageLayout from '@/components/ToolPageLayout';
import FileDropzone from '@/components/FileDropzone';
import PageToolWorkspace from '@/components/PageToolWorkspace';
import { ToolIcon } from '@/components/Icons';
import { loadPdfForRender } from '@/lib/renderUtils';
import { downloadBlob } from '@/lib/pdfUtils';
import { getToolById } from '@/lib/tools';

export default function AISummarizerClient() {
  const toolInfo = getToolById('summarizer') || {
    name: 'AI Summarizer',
    description: 'Generate concise summaries from PDF content',
    categoryColor: 'var(--tool-intelligence)',
    icon: 'brain',
  };

  const [file, setFile] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [summary, setSummary] = useState('');
  const [summarySentencesCount, setSummarySentencesCount] = useState(5);

  const handleFilesSelected = useCallback((files) => {
    const f = files[0];
    if (!f) return;
    setFile(f);
    setSummary('');
    setProgress(0);
  }, []);

  // Simple TF extractive summarizer
  const summarizeText = (text, sentencesCount = 5) => {
    // 1. Split into sentences
    const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
    if (sentences.length <= sentencesCount) return text;

    // 2. Tokenize and calculate word frequencies
    const words = text.toLowerCase().match(/\b[a-z]{3,}\b/g) || [];
    const stopWords = new Set([
      'the', 'and', 'a', 'to', 'of', 'in', 'is', 'that', 'it', 'on', 'for', 'this', 'with', 'as', 'was', 'at', 'by', 'an', 'be', 'or', 'are', 'from', 'at', 'about', 'but', 'not'
    ]);

    const wordFreq = {};
    words.forEach((w) => {
      if (!stopWords.has(w)) {
        wordFreq[w] = (wordFreq[w] || 0) + 1;
      }
    });

    // 3. Score sentences
    const scoredSentences = sentences.map((sentence, index) => {
      const sentenceWords = sentence.toLowerCase().match(/\b[a-z]{3,}\b/g) || [];
      let score = 0;
      sentenceWords.forEach((w) => {
        score += wordFreq[w] || 0;
      });
      return { sentence: sentence.trim(), score, index };
    });

    // 4. Sort by score and pick top N
    const topSentences = [...scoredSentences]
      .sort((a, b) => b.score - a.score)
      .slice(0, sentencesCount);

    // 5. Restore original reading order
    topSentences.sort((a, b) => a.index - b.index);

    return topSentences.map((s) => s.sentence).join(' ');
  };

  const handleSummarize = async () => {
    if (!file) return;
    setProcessing(true);
    setProgress(15);
    setSummary('');

    try {
      const pdf = await loadPdfForRender(file);
      let fullText = '';

      for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        const pageText = textContent.items.map((item) => item.str).join(' ');
        fullText += pageText + ' ';
        setProgress(Math.round(15 + (i / pdf.numPages) * 70));
      }

      setProgress(90);
      const generatedSummary = summarizeText(fullText, summarySentencesCount);
      setSummary(generatedSummary);
      setProgress(100);
    } catch (err) {
      alert('Error generating summary: ' + err.message);
    } finally {
      setProcessing(false);
    }
  };

  const downloadSummary = () => {
    if (!summary) return;
    const content = `Summary of: ${file.name}\nGenerated by PDF Section AI\n\n${summary}`;
    downloadBlob(
      new Blob([content], { type: 'text/plain;charset=utf-8' }),
      file.name.replace('.pdf', '_summary.txt'),
      'text/plain'
    );
  };

  return (
    <ToolPageLayout
      title={toolInfo.name}
      description={toolInfo.description}
      icon={toolInfo.icon}
      iconColor={toolInfo.categoryColor}
      showHeader={!file}
      layoutMode={file ? 'page-preview' : 'page-scroll'}
    >
      {!file ? (
        <FileDropzone
          accept=".pdf"
          multiple={false}
          onFilesSelected={handleFilesSelected}
          label="Upload your PDF to generate a local summary"
          id="summarizer-dropzone"
        />
      ) : (
        <PageToolWorkspace
          title={toolInfo.name}
          description={toolInfo.description}
          icon={toolInfo.icon}
          iconColor={toolInfo.categoryColor}
          file={file}
          onReset={() => {
            setFile(null);
            setSummary('');
            setProgress(0);
          }}
          preview={
            <div
              className="card"
              style={{
                padding: 'var(--space-lg)',
                minHeight: '260px',
                display: 'flex',
                flexDirection: 'column',
                gap: 'var(--space-md)',
                backgroundColor: 'rgba(255,255,255,0.01)',
                width: '100%',
              }}
            >
              <h3 className="body-md" style={{ fontWeight: 600, borderBottom: '1px solid var(--hairline)', paddingBottom: '8px' }}>
                Summary Result
              </h3>

              {processing && (
                <div style={{ margin: 'auto', width: '100%', maxWidth: '300px', textAlign: 'center' }}>
                  <div className="progress-track">
                    <div className="progress-fill" style={{ width: `${progress}%` }} />
                  </div>
                  <p className="caption ink-muted" style={{ marginTop: 'var(--space-xs)' }}>
                    Reading document text... {progress}%
                  </p>
                </div>
              )}

              {!processing && !summary && (
                <p className="body-sm ink-muted" style={{ fontStyle: 'italic', margin: 'auto', textAlign: 'center' }}>
                  Click "Generate Summary" in the sidebar to begin processing.
                </p>
              )}

              {!processing && summary && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
                  <p className="body-sm ink-subtle" style={{ lineHeight: 1.6, textAlign: 'justify' }}>
                    {summary}
                  </p>
                  
                  <button
                    className="btn btn-secondary"
                    onClick={downloadSummary}
                    style={{ alignSelf: 'flex-end', fontSize: '12px', padding: '6px 12px' }}
                  >
                    Download Summary (.txt)
                  </button>
                </div>
              )}
            </div>
          }
          footer={
            <button
              className="btn btn-primary btn-lg btn-attention"
              onClick={handleSummarize}
              disabled={processing}
              style={{ width: '100%' }}
              id="summarize-pdf-button"
            >
              {processing ? 'Processing...' : 'Generate Summary'}
              <ToolIcon name="brain" size={16} style={{ marginLeft: 6 }} />
            </button>
          }
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            <p className="eyebrow" style={{ color: 'var(--ink-subtle)' }}>Summary Options</p>
            
            <div>
              <label className="caption ink-muted" style={{ display: 'block', marginBottom: '6px' }}>Summary length (sentences):</label>
              <select
                className="input"
                value={summarySentencesCount}
                onChange={(e) => setSummarySentencesCount(parseInt(e.target.value))}
                style={{ width: '100%' }}
              >
                <option value={3}>Short (3 sentences)</option>
                <option value={5}>Medium (5 sentences)</option>
                <option value={10}>Long (10 sentences)</option>
                <option value={15}>Detailed (15 sentences)</option>
              </select>
            </div>
          </div>
        </PageToolWorkspace>
      )}
    </ToolPageLayout>
  );
}
